//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 26/10/2015 18:48:18
namespace SpaceShipDemo
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Models
            {
                
                /// <summary> Path to Content/Assets/Models/asteroid_1_0.fbx </summary>
                public const string asteroid_1_0_fbx = "Content/Assets/Models/asteroid_1_0.fbx";
                
                /// <summary> Path to Content/Assets/Models/asteroid_2_0.fbx </summary>
                public const string asteroid_2_0_fbx = "Content/Assets/Models/asteroid_2_0.fbx";
                
                /// <summary> Path to Content/Assets/Models/asteroid_3_0.fbx </summary>
                public const string asteroid_3_0_fbx = "Content/Assets/Models/asteroid_3_0.fbx";
                
                /// <summary> Path to Content/Assets/Models/asteroid_4_0.fbx </summary>
                public const string asteroid_4_0_fbx = "Content/Assets/Models/asteroid_4_0.fbx";
                
                /// <summary> Path to Content/Assets/Models/environment.fbx </summary>
                public const string environment_fbx = "Content/Assets/Models/environment.fbx";
                
                /// <summary> Path to Content/Assets/Models/ship.fbx </summary>
                public const string ship_fbx = "Content/Assets/Models/ship.fbx";
                
                /// <summary> Path to Content/Assets/Models/thrust.fbx </summary>
                public const string thrust_fbx = "Content/Assets/Models/thrust.fbx";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/engines_2.wav </summary>
                public const string engines_2_wav = "Content/Assets/Sounds/engines_2.wav";
                
                /// <summary> Path to Content/Assets/Sounds/explosion.wav </summary>
                public const string explosion_wav = "Content/Assets/Sounds/explosion.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/asteroids_d.png </summary>
                public const string asteroids_d_png = "Content/Assets/Textures/asteroids_d.png";
                
                /// <summary> Path to Content/Assets/Textures/asteroids_n.png </summary>
                public const string asteroids_n_png = "Content/Assets/Textures/asteroids_n.png";
                
                /// <summary> Path to Content/Assets/Textures/backPlanet.png </summary>
                public const string backPlanet_png = "Content/Assets/Textures/backPlanet.png";
                
                /// <summary> Path to Content/Assets/Textures/particleFire.png </summary>
                public const string particleFire_png = "Content/Assets/Textures/particleFire.png";
                
                /// <summary> Path to Content/Assets/Textures/shipDiffuse.jpg </summary>
                public const string shipDiffuse_jpg = "Content/Assets/Textures/shipDiffuse.jpg";
                
                /// <summary> Path to Content/Assets/Textures/shipEmmisive.jpg </summary>
                public const string shipEmmisive_jpg = "Content/Assets/Textures/shipEmmisive.jpg";
                
                /// <summary> Path to Content/Assets/Textures/shipSpecular.jpg </summary>
                public const string shipSpecular_jpg = "Content/Assets/Textures/shipSpecular.jpg";
                
                /// <summary> Path to Content/Assets/Textures/SmokeParticle.png </summary>
                public const string SmokeParticle_png = "Content/Assets/Textures/SmokeParticle.png";
                
                /// <summary> Path to Content/Assets/Textures/spaceBackground.cubemap </summary>
                public const string spaceBackground_cubemap = "Content/Assets/Textures/spaceBackground.cubemap";
                
                /// <summary> Path to Content/Assets/Textures/spaceIBL.cubemap </summary>
                public const string spaceIBL_cubemap = "Content/Assets/Textures/spaceIBL.cubemap";
                
                /// <summary> Path to Content/Assets/Textures/star.png </summary>
                public const string star_png = "Content/Assets/Textures/star.png";
                
                /// <summary> Path to Content/Assets/Textures/Thrust.png </summary>
                public const string Thrust_png = "Content/Assets/Textures/Thrust.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/asteroidMat.wmat </summary>
                public const string asteroidMat = "Content/Assets/Materials/asteroidMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/glassMat.wmat </summary>
                public const string glassMat = "Content/Assets/Materials/glassMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/MyMaterial.wmat </summary>
                public const string MyMaterial = "Content/Assets/Materials/MyMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/planetMat.wmat </summary>
                public const string planetMat = "Content/Assets/Materials/planetMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/shipMat.wmat </summary>
                public const string shipMat = "Content/Assets/Materials/shipMat.wmat";
                
                /// <summary> Path to Content/Assets/Materials/starMat.wmat </summary>
                public const string starMat = "Content/Assets/Materials/starMat.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
